name: Proxy ChartFox Charts

on:
  workflow_dispatch:
    inputs:
      icao:
        description: 'ICAO code'
        required: true
        default: 'LFPG'

jobs:
  fetch-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Appel API ChartFox
        run: |
          mkdir output
          curl -X GET "https://api.chartfox.org/v1/charts/${{ github.event.inputs.icao }}" \
            -H "Authorization: Bearer ${{ secrets.CHARTFOX_TOKEN }}" \
            -H "Accept: application/json" \
            -o output/${{ github.event.inputs.icao }}.json

      - name: Upload charts
        uses: actions/upload-artifact@v4
        with:
          name: charts-${{ github.event.inputs.icao }}
          path: output/${{ github.event.inputs.icao }}.json
